CLASS zcl_ce_vdmdiagramcds DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES if_rap_query_provider.

  PROTECTED SECTION.
  PRIVATE SECTION.
    CONSTANTS gc_max_rows TYPE i VALUE 500.
ENDCLASS.



CLASS ZCL_CE_VDMDIAGRAMCDS IMPLEMENTATION.


  METHOD if_rap_query_provider~select.
   " TO BE IMPLEMENTED
  ENDMETHOD.
ENDCLASS.
